index:
    pattern:   /
    defaults:  { _controller: ONNAesopGamesBundle:Page:index }
about:
    pattern:   /about
    defaults:  { _controller: ONNAesopGamesBundle:Page:about }
games:
    pattern:   /games
    defaults:  { _controller: ONNAesopGamesBundle:Page:games }
blog:
    pattern:   /blog
    defaults:  { _controller: ONNAesopGamesBundle:Page:blog }
contact:
    pattern:   /contact
    defaults:  { _controller: ONNAesopGamesBundle:Page:contact }
support:
    pattern:   /support
    defaults:  { _controller: ONNAesopGamesBundle:Page:greenlight }
greenlight_yes:
    pattern:   /greenlight_yes/{active}
    defaults:  { _controller: ONNAesopGamesBundle:Page:greenlightYes, active:'no' }
greenlight_no:
    pattern:   /greenlight_no
    defaults:  { _controller: ONNAesopGamesBundle:Page:greenlightNo }
navbar:
    pattern:   /navbar
    defaults:  { _controller: ONNAesopGamesBundle:Page:navbar }
perks:
    pattern:   /perks/{last_id}/{show}
    defaults:  { _controller: ONNAesopGamesBundle:Page:perks, last_id: '0','show': 'limited' }
looking_closer:
    pattern:   /looking_closer
    defaults:  { _controller: ONNAesopGamesBundle:Page:lookingCloser }
calendar:
    pattern:   /calendar
    defaults:  { _controller: ONNAesopGamesBundle:Page:calendar }
stretch:
    pattern:   /stretch/{id}/{show}
    defaults:  { _controller: ONNAesopGamesBundle:Page:stretch, id: '0','show': 'limited' }
packages:
    pattern:   /packages/{last_id}/{show}
    defaults:  { _controller: ONNAesopGamesBundle:Page:packages, last_id: '0','show': 'limited' }
press_kit:
    pattern:   /press_kit
    defaults:  { _controller: ONNAesopGamesBundle:Page:pressKit }
press_body:
    pattern:   /press_body/{content}
    defaults:  { _controller: ONNAesopGamesBundle:Page:pressBody }
oculus:
    pattern:   /oculus
    defaults:  { _controller: ONNAesopGamesBundle:Page:oculus }
parties:
    pattern:   /parties
    defaults:  { _controller: ONNAesopGamesBundle:Page:oculus }
party:
    pattern:   /party
    defaults:  { _controller: ONNAesopGamesBundle:Page:oculus }
event:
    pattern:   /event
    defaults:  { _controller: ONNAesopGamesBundle:Page:oculus }
events:
    pattern:   /events
    defaults:  { _controller: ONNAesopGamesBundle:Page:oculus }
local:
    pattern:   /local
    defaults:  { _controller: ONNAesopGamesBundle:Page:oculus }
