index:
    pattern:   /
    defaults:  { _controller: ONNAesopGamesBundle:Page:index }
about:
    pattern:   /about
    defaults:  { _controller: ONNAesopGamesBundle:Page:about }
games:
    pattern:   /games
    defaults:  { _controller: ONNAesopGamesBundle:Page:games }
blog:
    pattern:   /blog
    defaults:  { _controller: ONNAesopGamesBundle:Page:blog }
contact:
    pattern:   /contact
    defaults:  { _controller: ONNAesopGamesBundle:Page:contact }
support:
    pattern:   /support
    defaults:  { _controller: ONNAesopGamesBundle:Page:support }
navbar:
    pattern:   /navbar
    defaults:  { _controller: ONNAesopGamesBundle:Page:navbar }
perks:
    pattern:   /perks
    defaults:  { _controller: ONNAesopGamesBundle:Page:perks }
looking_closer:
    pattern:   /looking_closer
    defaults:  { _controller: ONNAesopGamesBundle:Page:lookingCloser }
stretch:
    pattern:   /stretch
    defaults:  { _controller: ONNAesopGamesBundle:Page:stretch }
packages:
    pattern:   /packages
    defaults:  { _controller: ONNAesopGamesBundle:Page:packages }
